
    (deffacts museo_datos
        (museo
            (id_museo 2)
            (distrito "Barranco")
            (puntaje_resena 4.3)
            (ha_inicio 10)
            (ha_fin 19)
            (hc_inicio 16)
            (hc_fin 18)
            (tarifa_normal 12.0)
            (tarifa_ninos 6.0)
            (tarifa_ancianos 6.0)
            (tarifa_discapacitados 12.0)
            (reserva_entrada false)
            (servicio_restaurante false)
            (servicio_cafeteria true)
            (servicio_guiado true)
            (servicio_biblioteca false)
            (venta_objetos true)
            (accesibilidad true)
            (permiso_foto true)
            (estacionamiento true)
            (visita_virtual false)
            (n_restaurantes_prox 1822)
            (n_atracciones_prox 230)
            (telefono true)
            (email true)
            (sitio_web true)
            (pag_facebook true)
            (pag_instagram true)
            (pag_tiktok true)
            (categoria "Arte")
            (dia_atencion "Martes" "MiÃ©rcoles" "Jueves" "Viernes" "Domingo")
            (dia_concurrido )
        )
    )
    